# -*- mode: python -*-
a = Analysis(['src\\pypdfocr.py'],
             pathex=['C:\\Users\\Virantha Ekanayake\\dev\\pypdfocr\\src'],
		hiddenimports = [
		    'reportlab.pdfbase._fontdata_enc_macexpert',
		    'reportlab.pdfbase._fontdata_enc_macroman',
		    'reportlab.pdfbase._fontdata_enc_pdfdoc',
		    'reportlab.pdfbase._fontdata_enc_standard',
		    'reportlab.pdfbase._fontdata_enc_symbol',
		    'reportlab.pdfbase._fontdata_enc_winansi',
		    'reportlab.pdfbase._fontdata_enc_zapfdingbats',
		    'reportlab.pdfbase._fontdata_widths_courier',
		    'reportlab.pdfbase._fontdata_widths_courierbold',
		    'reportlab.pdfbase._fontdata_widths_courierboldoblique',
		    'reportlab.pdfbase._fontdata_widths_courieroblique',
		    'reportlab.pdfbase._fontdata_widths_helvetica',
		    'reportlab.pdfbase._fontdata_widths_helveticabold',
		    'reportlab.pdfbase._fontdata_widths_helveticaboldoblique',
		    'reportlab.pdfbase._fontdata_widths_helveticaoblique',
		    'reportlab.pdfbase._fontdata_widths_symbol',
		    'reportlab.pdfbase._fontdata_widths_timesbold',
		    'reportlab.pdfbase._fontdata_widths_timesbolditalic',
		    'reportlab.pdfbase._fontdata_widths_timesitalic',
		    'reportlab.pdfbase._fontdata_widths_timesroman',
		    'reportlab.pdfbase._fontdata_widths_zapfdingbats'],
             hookspath=None,
             runtime_hooks=None)
pyz = PYZ(a.pure)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='pypdfocr.exe',
          debug=False,
          strip=None,
          upx=True,
          console=True )
